service: sf-demo
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: sqs:*
          Resource: !GetAtt TargetSQS.Arn

        - Effect: "Allow"
          Action:
            - dynamodb:UpdateItem

            - dynamodb:GetItem
          Resource: !GetAtt BooksTable.Arn

        - Effect: "Allow"
          Action:
            - dynamodb:UpdateItem

            - dynamodb:GetItem
          Resource: !GetAtt UsersTable.Arn

        - Effect: "Allow"
          Action:
            - states:*
          Resource: "*"

package:
  individually: true

functions:
  checkInventory:
    handler: functions/checkInventory.handler

  calculateTotal:
    handler: functions/calculateTotal.handler

  redeemPoints:
    handler: functions/redeemPoints.handler

  billCustomer:
    handler: functions/billCustomer.handler

  restoreRedeemPoints:
    handler: functions/restoreRedeemPoints.handler

  sqsWorker:
    handler: functions/sqsWorker.handler
    events:
      - sqs:
          arn: !GetAtt TargetSQS.Arn
          batchSize: 1

  restoreQuantity:
    handler: functions/restoreQuantity.handler

  rearmTaskToken:
    handler: functions/rearmTaskToken.handler

stepFunctions:
  stateMachines:
    storeCheckoutFlow:
      name: StoreCheckoutFlow
      definition:
        StartAt: CheckInventoryState
        States:
          CheckInventoryState:
            Type: Task
            Resource: !GetAtt checkInventory.Arn
            Next: CalculateTotalState
            Catch:
              - ErrorEquals: ["BookNotFound"]
                Next: BookNotFoundErrorState
                ResultPath: "$.bookNotFoundError"

              - ErrorEquals: ["BookOutOfStock"]
                Next: BookOutOfStockState
                ResultPath: "$.bookOutOfStockError"
            ResultPath: "$.book"

          BookNotFoundErrorState:
            Type: Pass
            Result: "No such book available"
            End: true

          BookOutOfStockState:
            Type: Pass
            Result: "The book is out of stock"
            End: true

          CalculateTotalState:
            Type: Task
            Resource: !GetAtt calculateTotal.Arn
            ResultPath: "$.total"
            Next: IsRedeemNeededState

          IsRedeemNeededState:
            Type: Choice
            Choices:
              - Variable: $.redeem
                BooleanEquals: true
                Next: RedeemPointsState
            Default: BillCustomerState

          RedeemPointsState:
            Type: Task
            Resource: !GetAtt redeemPoints.Arn
            Next: BillCustomerState
            Catch:
              - ErrorEquals: [States.ALL]
                Next: RedeemPointsErrorState
                ResultPath: "$.redeemPointsError"
            ResultPath: "$.total"

          BillCustomerState:
            Type: Task
            Resource: !GetAtt billCustomer.Arn
            Next: PrepareOrderState
            ResultPath: "$.billingStatus"
            Retry:
              - ErrorEquals: [States.ALL]
                MaxAttempts: 3
            Catch:
              - ErrorEquals: [States.ALL]
                Next: BillingErrorState
                ResultPath: "$.customerBillingError"

          PrepareOrderState:
            Type: Task
            Resource: arn:aws:states:::sqs:sendMessage.waitForTaskToken
            Parameters:
              QueueUrl: !Ref TargetSQS
              MessageBody:
                Input.$: "$"
                Token.$: "$$.Task.Token"
            ResultPath: "$.courierStatus"
            Catch:
              - ErrorEquals: ["NoCourierAvailable"]
                ResultPath: "$.courierError"
                Next: RefundCustomerState
            Next: RearmTaskTokenState

          RearmTaskTokenState:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
            Parameters:
              FunctionName: !GetAtt rearmTaskToken.Arn
              Payload:
                Input.$: "$"
                Token.$: "$$.Task.Token"
            ResultPath: "$.rearmStatus"
            Next: DispatchOrderState

          DispatchOrderState:
            Type: Task
            Resource: arn:aws:states:::sns:publish
            Parameters:
              TopicArn: !GetAtt NotifyCourierSNSTopic.TopicArn
              Message.$: "$"
            Next: DispatchedState
            ResultPath: "$.dispatchOrderEvent"

          DispatchedState:
            Type: Pass
            End: true
            Result: "Your order will be dispatched in 24 hours"
            ResultPath: "$.dispatchedStatus"

          RefundCustomerState:
            Type: Pass
            Result: "Customer is refunded"
            ResultPath: "$.refundStatus"
            Next: RestoreQuantityState

          RestoreQuantityState:
            Type: Task
            Resource: !GetAtt restoreQuantity.Arn
            ResultPath: "$.restoreQuantityStatus"
            Next: RestoreRedeemPointsState

          RestoreRedeemPointsState:
            Type: Task
            Resource: !GetAtt restoreRedeemPoints.Arn
            ResultPath: "$.redeemPointsStatus"
            End: true

          RedeemPointsErrorState:
            Type: Pass
            Result: "Error in redeeming points"
            End: true

          BillingErrorState:
            Type: Pass
            Result: "Error in billing a customer"
            ResultPath: "$.billingStatus"
            Next: RestoreRedeemPointsState

plugins:
  - serverless-step-functions
  - serverless-esbuild
  - serverless-iam-roles-per-function
  - serverless-prune-plugin

resources:
  Resources: ${file(resources.yml)}
  Outputs:
    MyStateMachine:
      Description: The ARN of the state machine
      Value:
        Ref: StoreCheckoutFlow
